<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/app.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));

$this->headScript()->prependFile($this->assetUrl('js/main.js'));

$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();

$url = $this->serverUrl(true);
//echo 'url:'.$url;
if (strpos($url, 'page/home') !== false) {
    $home = true;
}else{
  $home = false;
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>

        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>

        <!-- fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Noto+Serif:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
        
        <!-- scripts -->
        <?php echo $this->headScript(); ?>
        <script src="https://kit.fontawesome.com/582fb8c29f.js" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/colcade@0/colcade.js"></script>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    <nav class="nav">
      <div class="nav__nav-logo nav-logo">digital<span>Husserl</span></div>
      <ul class="nav-items">
        <?php $menu = $site->publicNav()->menu();
          $container = $menu->getContainer();
        ?>
        <?php foreach ($container as $page): ?>
            <?php if($page->isActive()): ?>
              <li class="nav-items__nav-item nav-item nav-text nav-active"><?= $menu->htmlify($page) ?></li>
            <?php else: ?>
              <li class="nav-items__nav-item nav-item nav-text"><?= $menu->htmlify($page) ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
      </ul>
      <div class="nav__nav-burger nav-burger burger-icon">
        <span class="burger-icon__burger-line burger-line"></span>
      </div>
    </nav>
    <div class="page content">    
      <?php echo $this->content; ?>            
    </div> 
  </body>
</html>