<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Menu\Form\MenuForm $form
 * @var string $name Empty string
 * @var array|null $jstree
 * @var array $linkedPages
 * @var array $notLinkedPages
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'add menus');
?>

<?= $this->pageTitle($translate('New menu'), 1, $translate('Menu')) ?>
<?php $this->trigger('view.add.before'); ?>
<?= $this->partial('menu/site-admin/menu/form', [
    'site' => $site,
    'form' => $form,
    'name' => $name,
    'jstree' => $jstree,
    'linkedPages' => $linkedPages,
    'notLinkedPages' => $notLinkedPages,
    'submitLabel' => $translate('Add'),
    'sectionNavEvent' => 'view.add.section_nav',
    'action' => 'add',
]) ?>

<?php $this->trigger('view.add.after'); ?>
