<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Menu\Form\MenuForm $form
 * @var string $name
 * @var array|null $jstree
 * @var array $linkedPages
 * @var array $notLinkedPages
 * @var string $submitLabel
 * @var string $deleteButton
 * @var string $sectionNavEvent
 * @var string $action
 *
 * Improved from application/src/view/omeka/site-admin/index/navigation.phtml.
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$navigationLink = $plugins->get('navigationLink');

$rightsEdit = $this->userIsAllowed(\Menu\Controller\SiteAdmin\MenuController::class, 'edit');
$rightsDelete = $this->userIsAllowed(\Menu\Controller\SiteAdmin\MenuController::class, 'delete');

$form = $rightsEdit && $form ? $form->prepare() : null;

$this->headLink()
    ->prependStylesheet($assetUrl('css/advanced-search.css', 'Omeka'))
    ->appendStylesheet($assetUrl('css/jstree.css', 'Omeka'))
    ->appendStylesheet($assetUrl('css/menu-admin.css', 'Menu'));
$this->headScript()
    ->appendFile($assetUrl('vendor/jstree/jstree.min.js', 'Omeka'))
    // ->appendFile($assetUrl(''js/site-navigation.js', 'Omeka'))
    ->appendFile($assetUrl('js/jstree-plugins.js', 'Omeka'))
    ->appendFile($assetUrl('js/advanced-search.js', 'Omeka'))
    ->appendFile($assetUrl('js/query-form.js', 'Omeka'))
    ->appendFile($assetUrl('js/menu-admin.js', 'Menu'));
?>

<?php if ($form): // Page menu/add or menu/edit. ?>
<?= $this->form()->openTag($form) ?>
<?= $this->formRow($form->get('csrf')) ?>
<?php endif; ?>

<div id="page-actions">
    <?= !$rightsEdit || $action === 'add' ? '' : $hyperlink($translate('Tops to menus'), $url('admin/site/slug/menu-id', ['menu-slug' => $name, 'action' => 'tops-to-menus'], true), ['class' => 'button', 'title' => $translate('Create a new menu for each top menu')]) ?>
    <?= $rightsDelete && isset($deleteButton) ? $deleteButton : '' ?>
    <?php if ($form): // Page menu/add or menu/edit. ?>
    <?php // The omeka cancel button cannot be used, because name may have been changed.?>
    <?= $hyperlink($translate('Cancel'), $url('admin/site/slug/menu-id', ['menu-slug' => $name, 'action' => 'show'], true), ['class' => 'show-cancel button']) ?>
    <button type="submit" class="button"><?= $escape($submitLabel) ?></button>
    <?php else: // Page menu/show. ?>
    <?= $hyperlink($translate('Edit'), $url('admin/site/slug/menu-id', ['menu-slug' => $name, 'action' => 'edit'], true), ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<div class="toolbar-actions">
    <button id="tree-open-all" type="button" class="button"><?= $translate('Open all') ?></button>
    <button id="tree-close-all" type="button" class="button"><?= $translate('Close all') ?></button>
</div>

<div id="nav-tree"
    data-link-form-url="<?= $form ? $escapeAttr($url('admin/site/slug/action', ['action' => 'navigation-link-form'], true)) : '' ?>"
    data-jstree-data="<?= $escapeAttr(json_encode($jstree, 320)) ?>"
    data-menu-name="<?= $escapeAttr($name) ?>"
    data-jstree-url="<?= $action === 'add' ? '' : $escapeAttr($url('admin/site/slug/menu-id', ['action' => 'jstree'], true)) ?>"
    >
</div>

<?php if ($form): ?>

<button id="nav-selector-button" class="button mobile-only"><?= $translate('Add a link to a site page') ?></button>
<div id="nav-selector" class="always-open sidebar">
    <a href="#" class="mobile-only sidebar-close o-icon-close"><span class="screen-reader-text"><?= $translate('Close') ?></span></a>

    <?= $this->formRow($form->get('name')) ?>
    <?php /*
    <div class="field">
        <label for="o:homepage[o:id]"><?php echo $translate('Select a homepage'); ?></label>
        <?php echo $this->formElement($form->get('o:homepage[o:id]')); ?>
    </div>
    */ ?>
    <div class="field">
        <label for="nav-custom-links"><?= $translate('Add a custom link') ?></label>
        <div id="nav-custom-links">
            <?php foreach ($navigationLink->getCustomTypes() as $type): ?>
            <?php $name = $navigationLink->getName($type); ?>
            <button
                type="button"
                draggable="true"
                data-type="<?= $escape($type) ?>"
                data-value="<?= $escape($type) ?>"
                class="button option"
                ><?= $escape($translate($name)) ?></button>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="field">
        <label><?= $translate('Add a link to a site page') ?></label>
        <?php // Display only pages that are not yet included in this menu. ?>
        <?php $pages = $notLinkedPages; ?>
        <?php if (count($pages)): ?>
        <input type="text" class="page-selector-filter" placeholder="<?= $translate('Filter pages') ?>" aria-label="<?= $translate('Filter pages') ?>">
        <div id="nav-page-links">
        <?php foreach ($pages as $page): ?>
            <button class="nav-page-link option active"
                type="button"
                class="button"
                data-type="page"
                data-label="<?= $escape($page->title()) ?>"
                data-id="<?= $escape($page->id()) ?>"
                data-slug="<?= $escape($page->slug()) ?>"
                data-is_public="<?= $page->isPublic() ? '1' : '0' ?>">
                <?= sprintf('%s (%s)', $escape($page->title()), $escape($page->slug())) ?>
                <?php if (!$page->isPublic()): ?>
                <span class="o-icon-private" aria-label="<?= $translate('Private') ?>" title="<?= $translate('Private') ?>" role="presentation"></span>
                <?php endif; ?>
            </button>
        <?php endforeach; ?>
        </div>
        <?php else: ?>
        <p><?= $translate('There are no available pages.') ?></p>
        <?php endif; ?>
    </div>
    <?= $this->form()->closeTag() ?>
</div>
<?php endif; ?>
