<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Site\Navigation\Link\LinkInterface $link
 * @var array|null $data
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$data = empty($data) ? [] : $data;
$label = $data['label'] ?? null;
$id = $data['id'] ?? null;
$resource = null;
$resourceLabel = null;
if ($id) {
    try {
        /** @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource */
        $resource = $this->api()->read('resources', ['id' => $id])->getContent();
        $resourceLabel = $resource->displayTitle();
    } catch (\Throwable $e) {
    }
}
?>

<label><?= $translate('Type') ?>
    <input type="text" value="<?= $escape($translate($link->getName())) ?>" disabled="disabled"/>
</label>
<?php if ($resource): ?>
<label><?= $escape($translate(ucfirst(strtr($resource->getControllerName(), ['-' => ' '])))) ?>
    <input type="text" value="<?= $escape($resourceLabel) ?>" disabled="disabled"/>
</label>
<?php endif; ?>
<label><?= $translate('Label') ?>
    <input type="text" data-name="label" value="<?= $escape($label) ?>"/>
</label>
<label><?= $translate('Resource id') ?>
    <input type="number" data-name="id" value="<?= $id ? (int) $id : '' ?>" min="1" required="required"/>
    <?php if ($id && !$resource): ?>
    <span style="float: right; color: red; font-weight: normal;"><?= $escape($translate('Resource unavailable')) ?></span>
    <?php endif; ?>
</label>
<?php if ($resource): ?>
<div class="meta-group" style="font-weight: normal;">
    <label>
        <?= $translate('Visibility') ?>
        <span style="float: right;"><?= $resource->isPublic() ? $translate('Public') : $translate('Private') ?></span>
    </label>
    <?php if ($template = $resource->resourceTemplate()): ?>
    <label>
        <?= $translate('Resource template') ?>
        <span style="float: right;"><?= $translate($template->label()) ?></span>
    </label>
    <?php endif; ?>
    <?php if ($class = $resource->resourceClass()): ?>
    <label>
        <?= $translate('Resource class') ?>
        <span style="float: right;"><?= $translate($class->localName()) ?></span>
    </label>
    <?php endif; ?>
</div>
<?php endif; ?>
