<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Site\Navigation\Link\LinkInterface $link
 * @var array|null $data
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$data = empty($data) ? [] : $data;
$label = $data['label'] ?? null;
$class = $data['class'] ?? null;
?>

<label><?= $translate('Type') ?>
    <input type="text" value="<?= $escape($translate($link->getName())) ?>" disabled="disabled"/>
</label>
<label><?= $translate('Optional label') ?>
    <input type="text" data-name="label" value="<?= $escape($label) ?>"/>
</label>
<label><?= $translate('Optional html class') ?>
    <input type="text" data-name="class" value="<?= $escape($class) ?>"/>
</label>
