<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation|null $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation|null $itemSet
 */

if (!isset($response)) return;

$searchFacets = $searchConfig->subSetting('facet', 'facets', []);
if (!count($searchFacets)) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$isFacetModeButton = !in_array($searchConfig->subSetting('facet', 'mode'), ['link', 'js']);
$displayActive = (bool) $searchConfig->subSetting('facet', 'display_active', true);
$displayRefine = (bool) $searchConfig->subSetting('facet', 'display_refine', true);
$labelRefine = $displayRefine ? $searchConfig->subSetting('facet', 'label_refine', $translate('Refine search')) : null;
$displayFacetButton = $isFacetModeButton && ($displayActive || !empty($facets));
$displaySubmit = $displayFacetButton ? $searchConfig->subSetting('facet', 'display_submit', 'above') : 'none';
$labelSubmit = $displaySubmit ? $searchConfig->subSetting('facet', 'label_submit', $translate('Apply facets')) : null;
$displayReset = $searchConfig->subSetting('facet', 'display_reset', 'above');
$labelReset = $displayReset ? $searchConfig->subSetting('facet', 'label_reset', $translate('Reset facets')) : null;

$facetActives = $plugins->get('facetActives');
$facetElements = $plugins->get('facetElements');

// TODO Remove item sets facets early when item set redirects to search.
// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}
?>

<div id="search-facets" class="browse-search-aside__facet-items facet-items facets">
    <?php if ($displayActive && count($activeFacets)): ?>
        <div class="facet-items__active-facets active-facets">
            <?= $facetActives(null, $activeFacets, $searchConfig->setting('facet')) ?>
        </div>
    <?php endif; ?>

    <form id="form-facets" class="facet-items__facet-item-form facet-item-form">
        <?php //searchbar ?>
        <?php if ($displayRefine): ?>
            <div class="facets-refine">
                <input id="search-refine" name="refine" class="search-refine" value="<?= $escape($query->getQueryRefine()) ?>"<?= $labelRefine ? ' data-placeholder="' . $escapeAttr($labelRefine) . '"' : '' ?>/>
                <button id="search-refine-submit" class="search-refine" type="submit"><?= $escape($translate('Submit')) ?></button>
            </div>
        <?php endif; ?>
        <?php //if there ar no facets to apply than i got the text No filters available?>
        <?php if (empty($facets) && empty($activeFacets)): ?>
            <?php if ($label = $searchConfig->subSetting('facet', 'label_no_facets', $translate('No filters available'))): ?>
                <p><?= $escape($label) ?></p>
            <?php endif; ?>
        <?php else: ?>
            <ul class="facet-item-form__facets-list facets-list">
                <?php foreach ($facets as $name => $facetValues): ?>
                    <?php $facetParams = $searchFacets[$name]; ?>
                    <?php $hasState = in_array($facetParams['state'] ?? '', ['expand', 'collapse', 'collapse_unless_set']); ?>
                    <li class="facet-item<?= empty($facetParams['attributes']['class']) ? '' : ' ' . $escapeAttr($facetParams['attributes']['class']) ?>">
                        <?php if ($hasState): ?>
                            <?php $stateExpand = $facetParams['state'] === 'expand' || ($facetParams['state'] === 'collapse_unless_set' && !empty($activeFacets[$name])); ?>
                            <button type="button" class="facet-button facet-item__facets-item-top facets-item-top big-body-text <?= $stateExpand ? 'collapse' : 'expand' ?>" aria-label="<?= $translate($stateExpand ? 'Collapse' : 'Expand') ?>" data-label-expand="<?= $translate('Expand') ?>" data-label-collapse="<?= $translate('Collapse') ?>"><?= $escape($translate($facetParams['label'] ?? $name)) ?></button>
                        <?php else: ?>
                            <h4><?= $escape($translate($facetParams['label'] ?? $name)) ?></h4>
                        <?php endif; ?>
                        <div class="facet-elements<?= $hasState ? ' collapsible' : '' ?>"<?= $hasState && $facetParams['state'] === 'collapse' ? ' hidden="hidden"' : '' ?>>
                            <?= $facetElements($name, $facetValues, $facetParams) ?>
                            <?php if (($facetParams['more'] ?? '') !== '' && in_array($facetParams['type'] ?? '', ['', 'Checkbox', 'Link', 'Tree', 'TreeLink', 'Thesaurus', 'ThesaurusLink']) && count($facetValues) > (int) $facetParams['more']): ?>
                                <div class="facet-see-more">
                                    <button type="button" class="facet-see-more-or-less expand" data-default-count="<?= (int) $facetParams['more'] ?>" data-more-count="<?= count($facetValues) - (int) $facetParams['more'] ?>" data-label-see-more="<?= $escapeAttr($translate('See more')) ?>" data-label-see-less="<?= $escapeAttr($translate('See less')) ?>"><?= $escape($translate('See more')) ?></button>
                                </div>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <?php $displayButtonReset = $displayReset === 'below' || $displayReset === 'both'; ?>
        <?php $displayButtonSubmit = $displayFacetButton && ($displaySubmit === 'below' || $displaySubmit === 'both'); ?>
        <?php if ($displayButtonReset || $displayButtonSubmit): ?>
            <div class="facets-actions facets-actions-bottom">
                <?php if ($displayButtonSubmit): ?>
                <button id="facets-apply" class="facets-apply" type="submit"><?= $escape($labelSubmit) ?></button>
                <?php endif; ?>
                <?php if ($displayButtonReset): ?>
                <button id="facets-reset" class="facets-reset" type="reset"><?= $escape($labelReset) ?></button>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </form>
</div>
