<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2025
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation|null $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \Omeka\Api\Representation\ItemSetRepresentation|null $itemSet
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 *
 * For block layout:
 * @var bool $skipFormAction Remove action of the form, so it uses current page.
 */

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$api = $plugins->get('api');
$vars = $this->vars();
$variables = $vars->getArrayCopy();

$isPartial = !$site;
$skipFormAction = !empty($skipFormAction);

$lang = $this->lang();

$documentCount = $response->getTotalResults();
$displayParts = $searchConfig->setting('results', []);
$displayPartsHeader = array_filter($displayParts, fn ($v) => in_array($v, ['header', 'both']));
$displayPartsFooter = array_filter($displayParts, fn ($v) => in_array($v, ['footer', 'both']));
$displayFacets = $displayParts ? $displayParts['facets'] ?? 'before' : 'none';

$this->headLink()->appendStylesheet($assetUrl('css/search.css', 'AdvancedSearch'));
$this->headScript()->appendFile($assetUrl('js/search.js', 'AdvancedSearch'), 'text/javascript', ['defer' => 'defer']);
$this->htmlElement('body')->appendAttribute('class', 'search-page item-set resource browse');
?>

<div class="container search">
    <div class="search__search-page-top search-page-top">
        <div class="container__page-breadcrumb page-breadcrumb">
            <ul class="page-breadcrumb__breadcrumb-list breadcrumb-list">
                <li class="breadcrumb-listt_breadcrumb-item breadcrumb-item body-text"><a href="<?= $site->url();?>">Home</a></li>
                <li class="breadcrumb-listt_breadcrumb-item breadcrumb-item body-text"><a href="<?= $site->url();?>/collections">Collections</a></li>
                <li class="breadcrumb-listt_breadcrumb-item breadcrumb-item body-text"><a href="<?= $searchConfig->siteUrl()?>">Search</a></li>
            </ul>
        </div>
        <div class="search-page-top__page-top-info page-top-info">
            <h1 class="page-top-info__page-title page-title h1">The collection items</h1>
            <p class="page-top-info__page-info page-info body-text">
                Lorem ipsum dolor sit amet consectetur. Laoreet nisl tincidunt sit est. Nulla pellentesque neque tellus dolor lectus. Dictumst et nunc nec volutpat justo diam ac nam. Magna ultricies porttitor sagittis aliquet blandit purus pellentesque tempor. 
            </p>
        </div>
    </div>
    <div class="search__search-wrapper search-wrapper">
        <aside class="search-wrapper__browse-search-aside browse-search-aside">
            <div class="browse-search-aside__search-aside search-aside search-nav search-nav">
                <div class="search-nav__nav-aside-item nav-aside-item active">
                    <a href="<?= $site->url() ?>/search" class="nav-aside-item__nav-aside-item-text nav-aside-item-text filter-item-nav">Filter</a>
                    <div class="nav-aside-item__nav-aside-item-icon nav-aside-item-icon filter-icon">          
                        <svg width="30" height="27" viewBox="0 0 30 27" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M0.677991 1.5502L0.679868 1.54629C0.983287 0.907569 1.62722 0.5 2.34372 0.5H27.6592C28.3757 0.5 29.0196 0.907569 29.323 1.54629C29.6266 2.18542 29.5349 2.93746 29.084 3.48549C29.0839 3.48553 29.0839 3.48558 29.0839 3.48562L18.3661 16.4829L18.2519 16.6214V16.801V24.1925C18.2519 24.706 17.9613 25.1772 17.4941 25.407C17.0205 25.6398 16.4657 25.5905 16.0507 25.2806L16.0501 25.2801L12.2996 22.4887L12.2972 22.4869C11.9525 22.2335 11.751 21.8315 11.751 21.401V16.801V16.6214L11.6368 16.4828L0.913473 3.48016C0.913371 3.48004 0.913269 3.47991 0.913168 3.47979C0.466625 2.93584 0.372343 2.17948 0.677991 1.5502Z" stroke="#202020"/>
                        </svg>
                    </div>
                </div>
                <div class="search-nav__nav-aside-item nav-aside-item middle-item">
                    <p class="nav-aside-item__nav-aside-item-text nav-aside-item-text">|</p>
                </div>
                <div class="search-nav__nav-aside-item nav-aside-item browse-item-nav">
                    <a href="<?= $site->url() ?>/item/browse" class="nav-aside-item__nav-aside-item-text nav-aside-item-text">Browse</a>
                    <div class="nav-aside-item__nav-aside-item-icon nav-aside-item-icon browse-icon">
                        <svg width="31" height="30" viewBox="0 0 31 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M20.8847 0.904337L20.8861 0.905667L21.664 1.67777C21.6643 1.678 21.6645 1.67823 21.6647 1.67846C22.1088 2.12218 22.7098 2.375 23.3418 2.375H29.125C29.886 2.375 30.5 2.98903 30.5 3.75V11.25C30.5 12.011 29.886 12.625 29.125 12.625H16C15.239 12.625 14.625 12.011 14.625 11.25V1.875C14.625 1.11403 15.239 0.5 16 0.5H19.9141C20.2778 0.5 20.6257 0.645352 20.8847 0.904335L20.8847 0.904337ZM16 17.375H16.0007L19.9141 17.3691C19.9143 17.3691 19.9145 17.3691 19.9147 17.3691C20.2782 17.3693 20.6259 17.5146 20.8847 17.7735L21.664 18.5528C22.1082 18.9969 22.7095 19.25 23.3418 19.25H29.125C29.886 19.25 30.5 19.864 30.5 20.625V28.125C30.5 28.886 29.886 29.5 29.125 29.5H16C15.239 29.5 14.625 28.886 14.625 28.125V18.75C14.625 17.989 15.239 17.375 16 17.375Z" stroke="black"/>
                            <path d="M1 1.875V6.5625M10.375 24.375H1V6.5625M1 6.5625H9.4375" stroke="black" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </div>
                </div>
            </div>
            <?= $partial('search/facets-list') ?>
        </aside>
        <div class="search-wrapper__search-results search-results">
            <?php if ($displayPartsHeader): ?>
                <div class="search-results-part search-results-header">
                    <?= $partial('search/results-header-footer', $variables + ['resultPart' => 'header']) ?>
                </div>
            <?php endif; ?>
            <?php if ($documentCount): ?>
                <div class="search-results__search-results-part search-results-part search-results-list">
                    <?php foreach (array_filter($response->getResourceTotalResults()) as $resourceType => $count): ?>
                        <?= $partial('search/results', $variables + ['resourceType' => $resourceType]) ?>
                    <?php endforeach; ?>
                </div>
            <?php else: ?>
                <div class="noresults">
                    <?php if (empty($query) && !$itemSet): ?>
                        <?= $translate('Fill a query and get results.') ?>
                    <?php elseif (empty($query) && $itemSet): ?>
                        <?= $translate('This item set has no items.') ?>
                    <?php else: ?>
                        <?php if (in_array($searchConfig->subSetting('results', 'search_filters', 'header'), ['header', 'both'])): ?>
                            <div class="search-results-part search-results-header">
                                <?= $searchConfig->renderSearchFilters($query, ['template' => 'common/search-filters-links']) ?>
                            </div>
                        <?php endif; ?>
                        <?= $translate('The query returned no results') ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <?php if ($displayPartsFooter): ?>
                <div class="search-results-part search-results-footer">
                    <?= $partial('search/results-header-footer', $variables + ['resultPart' => 'footer']) ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

