<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 1);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>
<div id="content">
    <?php
    $nav = $site->publicNav();
    $container = $nav->getContainer();
    $activePage = $nav->findActive($container);
    //$type = $this->pagesMetadata('type') ?: null;
    //$next = $this->pagesMetadata('next',$page) ?: null;
    //$previous = $this->pagesMetadata('previous',$page) ?: null;

    if ($activePage):
      if ($activePage['depth'] !== 0): ?>
      <div class="container">
        <div id="portal-breadcrumbs" class="breadcrumbs" style="display:block;">
          <span class="breadcrumb-item">
              <a href="<?php echo $site->url();?>">Home</a>
          </span>
          <span class="breadcrumb-item" dir="ltr">
          <?php echo $nav->breadcrumbs()->setSeparator('</span><span class="breadcrumb-item" dir="ltr">'); ?>
      </span>

        </div>
      </div>
      <?php endif; ?>
    <?php endif; ?>
<!--
<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>
<?php endif; ?>-->

<?php $this->trigger('view.show.before'); ?>
<?php echo $this->content; ?>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php //echo $this->sitePagePagination(); ?>
<?php endif; ?>

</div>