<?php
$translate = $this->plugin('translate');
$thumbnailHelper = $this->plugin('thumbnail');
$locale = array(
  "en-US" => "en",
  "nl-NL" => "nl",
);
$lang = $locale[$this->lang()];

?>
<style>
  .card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
    padding-top: 0%;
  }
</style>
<section class="section">
  <div class="container">
    <?php if ($this->heading): ?>
      <h2><?php echo $this->heading; ?></h2>
    <?php endif; ?>

    <?php if($block->dataValue('text')):?>
      <p>
        <?php echo $block->dataValue('text');?>
      </p>
    <?php endif; ?>

    <?php if($this->resources):?>
      <?php
      $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
      $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
      ?>
      <div class="row">
        <?php  
        foreach ($this->resources as $resource):
          $heading = $resource->value($headingTerm, ['default' => $translate('[Untitled]'),'lang' => $lang]);
          $body = $resource->value('dcterms:description',['lang' => $lang]);
          if($resourceType == 'item-set'):
            $body = $resource->value('dcterms:description',['lang' => $lang]);
          endif;
          $type = $resource->resourceTemplate();
          if($type):
            $type= $type->label();
          elseif($resourceType == 'item-set'):
            $type= 'Collection';
          else:
            $type= "Object";
          endif;
        ?>          
      
        <?php
          $mediaurl = "";

          if($resourceType == 'item-set' && $resource->thumbnail()):
            $media = $resource->thumbnail();            
            if($media):
              if(sizeof($this->resources) <= 2):
                $mediaurl = str_replace('http:','',$media->assetUrl('large'));
              else:
                $mediaurl = str_replace('http:','',$media->assetUrl('medium'));
              endif;
            endif;
          elseif($resource->primaryMedia()):
            $media = $resource->primaryMedia();
            if($media):
              if(sizeof($this->resources) <= 2):
                $mediaurl = str_replace('http:', '', $media->thumbnailUrl('large'));
              else:
                $mediaurl = str_replace('http:', '', $media->thumbnailUrl('medium'));
              endif;
            endif;
          endif;
          $url = $resource->url();
        ?>

        <div class="col-xs-12 col-md-4">
          <div class="kul-card-image card card-gray">
            <?php if($mediaurl):?>
              <a href="<?php echo $resource->url();?>">
              <div class="card-img-top" style="background-image: url(<?php echo  $mediaurl;?>)">&nbsp;</div>
              </a>
            <?php endif;?>
            <div class="card-body">
            <h2>
              <a href="<?php echo $resource->url();?>"><?php echo $resource->value('dcterms:title');?></a>
            </h2>
            <?php if($resource->value('dcterms:date')):?>
              <h6><?php echo date('d-m-Y',strtotime($resource->value('dcterms:date')));?></h6>
            <?php endif;?>
            <?php $body = $resource->value('dcterms:description');?>
            <?php if ($body): ?>
              <?php
                if(strlen($body) > 200):
                  $body = substr($body, 0, 200);
                  $body = substr($body, 0, strrpos($body, ' ')).' ...';
                endif;
              ?>
              <p>
                <?php echo $body; ?>
              </p>
            <?php endif; ?>
            <?php if($lang == "en"):?>
            <a class="more" href="<?php echo $resource->url();?>">Read more</a>
            <?php else:?>
              <a class="more" href="<?php echo $resource->url();?>">Lees meer</a>
            <?php endif;?>  
            </div>
          </div>
        </div>
      <?php endforeach; ?>
      </div>
    <?php endif;?>  
        
   
      <?php if ($this->linkText):?>
        <div style="text-align:right;">
          <?php if($this->linkText == 'All collections'):?>
            <p>
              <strong>
                <a class="more" href="<?php echo $block->page()->site()->url().'/item-set';?>" class="button is-white">
                  <?php echo $this->linkText;?>
                </a>
              </strong>
            </p>
          <?php else:?>
            <p>
              <strong>
                <a class="more" href="<?php echo $block->page()->site()->url().'/page/'.strtolower($type);?>" class="button is-white">
                  <?php echo $this->linkText;?>
                </a>
              </strong>
            </p>
          <?php endif;?>
        </div>
      <?php endif;?>
    
  </div>
</section>  