<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \OaiPmhHarvester\Form\HarvestForm $form
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')
    ->appendAttribute('class', 'oai-pmh-harvester oai-pmh-harvester-index');

$this->headLink()
    ->appendStylesheet($assetUrl('css/oai-pmh-harvester.css', 'OaiPmhHarvester'));
$this->headScript()
    ->appendFile($assetUrl('js/oai-pmh-harvester.js', 'OaiPmhHarvester'));
?>

<?= $this->pageTitle($translate('Harvester'), 1, $translate('OAI-PMH')) ?>

<div id="page-actions">
    <button form="harvest-repository-form" type="submit" class="button"><?= $translate('View sets') ?></button>
</div>

<nav class="section-nav">
    <?= $this->navigation('Laminas\Navigation\OaiPmhHarvester')->menu() ?>
</nav>

<h3><?= $translate('Set repository to harvest') ?></h3>

<?= $this->form($form) ?>
