<!-- text/contact with border -->
<div class="section section--default">
    <div class="container">
        <div class="panel panel--light panel--border panel--full">
            <div class="grid">
                <div class="grid__12 grid__6@med">
                  <span class="spacer panel__content">
                      <h2><?php echo $block->dataValue('title');?></h2>
                      <?php echo $block->dataValue('text');?>
                  </span>

                  <?php if($block->dataValue('link')):?>
                  <div class="spacer">
                      <a href="<?php echo $block->dataValue('link');?>" class="btn spacer">Meer lezen</a>
                  </div>
                  <?php endif;?>
                </div>
                <div class="grid__12 grid__6@med">
                    <div class="panel">
                        <div class="grid">
                            <div class="grid__12 grid__4@med">
                                <div class="">
                                  <?php
                                    if($attachments):
                                      $media = $attachments[0]->media();           
                                          if($media):
                                            $url = $media->thumbnailUrl('square');
                                            $url = str_replace('http:', '', $url);
                                            echo '<img src="'.$url.'" />';
                                          endif;
                                    endif;
                                  ?>
                                </div>
                            </div>
                            <div class="grid__12 grid__8@med">
                                <div>
                                    <?php if($block->dataValue('functie')):?>
                                      <div class="text--uppercase text--secondary spacer">
                                          <?php echo $block->dataValue('functie');?>
                                      </div>
                                    <?php endif;?>
                                    <h3 class="spacer spacer--xsm"><?php echo $block->dataValue('name');?></h3>
                                    <div class="spacer">
                                        <span class="icon icon--phone"></span> <a href="tel:011223344"><?php echo $block->dataValue('tel');?></a><br>
                                        <span class="icon icon--mail"></span> <a href="mailto:<?php echo $block->dataValue('mail');?>"><?php echo $block->dataValue('mail');?></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
