<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$not = array('Description','Title');
$notalt = array('korte beschrijving', 'Collectie ID','Referenties object','Beeld','Beeld copyright');
?>

<?php foreach ($templateProperties as $term => $property): ?>
  <?php 
    if($property->isPrivate()):
      continue;
    endif;
    $propertyData = '';
    if(isset($values[$property->property()->term()])):
      $propertyData = $values[$property->property()->term()];
    else:
      continue;
    endif;
  ?>  
  <?php if(!in_array($propertyData['property']->label(),$not) && !in_array($propertyData['alternate_label'],$notalt)):?>
  <div class="row">
    <div class="col-xs-12 col-md-3">
      <h4 style="font-size:0.9rem;padding-top:0.3rem;padding-bottom:0.3rem;line-height: 1.6;">
      <?php if ($propertyData['alternate_label']): ?>
      <?php echo $escape($propertyData['alternate_label']); ?>
      <?php else: ?>
      <?php echo $escape($translate($propertyData['property']->label())); ?>
      <?php endif; ?>
      <?php if ('term' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
      <?php elseif ('vocab' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
      <?php endif; ?>
      </h4>
    </div>
    <div class="col-xs-12 col-md-9">
      <div class="values" style="font-size:0.9rem;padding-top:0.3rem;padding-bottom:0.3rem;line-height: 1.6;">
      <?php $i=0;?>
      <?php foreach ($propertyData['values'] as $value): ?>
          <?php
          $valueType = $value->type();
          $class = ['value'];
          if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
              $class[] = 'resource';
              $class[] = $escape($value->valueResource()->resourceName());
          } elseif ('uri' == $valueType) {
              $class[] = 'uri';
          }
          if (!$value->isPublic()) {
              $class[] = 'private';
          }
          ?>

            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">                
                  <?php echo $value->asHtml(); ?>
            </div>
            <?php $i++;?>
      <?php endforeach; ?>
      </div>
    </div>
  </div>
  <?php endif;?>
<?php endforeach; ?>
